version: '3.8'

services:
  db:
    image: postgres:13-alpine
    restart: unless-stopped
    env_file: ./.env
    volumes:
      - db_value:/var/lib/postgresql/data/

  backend:
    image: ${DOCKER_USERNAME}/foodgram_backend:latest
    restart: unless-stopped
    env_file: ./.env
    depends_on:
      - db
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/

  frontend:
    image: ${DOCKER_USERNAME}/foodgram_frontend:latest
    restart: unless-stopped

  nginx:
    image: nginx:1.25-alpine
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx.production.conf:/etc/nginx/conf.d/default.conf:ro
      - static_value:/var/html/static/
      - media_value:/var/html/media/

volumes:
  db_value:
  static_value:
  media_value:
