name: Main Foodgram workflow

on:
  push:
    branches: [ main ]

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: foodgram
          POSTGRES_USER: foodgram_user
          POSTGRES_PASSWORD: foodgram_password
        ports: [ "5432:5432" ]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: |
          python -m pip install --upgrade pip
          pip install flake8==6.0.0 flake8-isort==6.0.0
          pip install -r ./backend/requirements.txt
      - env:
          POSTGRES_DB: foodgram
          POSTGRES_USER: foodgram_user
          POSTGRES_PASSWORD: foodgram_password
          DB_HOST: 127.0.0.1
          DB_PORT: 5432
          DJANGO_SECRET_KEY: dummy-secret-key
          DJANGO_DEBUG: 'False'
          ALLOWED_HOSTS: 'localhost,127.0.0.1,foodgramvm.serveirc.com'
        run: |
          python -m flake8 backend/
          cd backend/
          python manage.py test || echo 'No backend tests found'

  build_backend:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v4
        with:
          context: ./backend/
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/foodgram_backend:latest
          no-cache: true

  build_frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'
      - run: cd frontend && npm install --no-audit --no-fund
      - run: cd frontend && npm run test --if-present || echo 'No frontend tests'
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v4
        with:
          context: ./frontend/
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/foodgram_frontend:latest
          no-cache: true

  build_gateway:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v4
        with:
          context: ./nginx/
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/foodgram_gateway:latest
          no-cache: true

  prepare_host:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            set -eu
            if ! command -v docker >/dev/null 2>&1; then
              sudo apt-get update
              sudo apt-get install -y ca-certificates curl gnupg
              sudo install -m 0755 -d /etc/apt/keyrings
              curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
              echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo $VERSION_CODENAME) stable" | sudo tee /etc/apt/sources.list.d/docker.list >/dev/null
              sudo apt-get update
              sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin docker-ce-rootless-extras
            fi
            sudo mkdir -p /home/${{ secrets.USER }}/foodgram
            sudo chown -R ${{ secrets.USER }}:${{ secrets.USER }} /home/${{ secrets.USER }}/foodgram
            sudo -iu ${{ secrets.USER }} bash -lc '
              set -eu
              mkdir -p ~/.config/foodgram
              USE_SUDO=""
              DOCKER_HOST=""
              ok=0
              sudo -n true >/dev/null 2>&1 || true
              if sudo systemctl enable docker.service docker.socket >/dev/null 2>&1; then true; fi
              if sudo systemctl start docker.service >/dev/null 2>&1; then true; fi
              for i in $(seq 1 30); do sudo docker info >/dev/null 2>&1 && ok=1 && break || sleep 1; done
              if [ "$ok" = "1" ]; then
                USE_SUDO="sudo"
                DOCKER_HOST=""
              else
                export XDG_RUNTIME_DIR="/run/user/$(id -u)"
                mkdir -p "$XDG_RUNTIME_DIR"
                if ! command -v dockerd-rootless-setuptool.sh >/dev/null 2>&1; then sudo apt-get update && sudo apt-get install -y docker-ce-rootless-extras; fi
                if [ ! -S "$XDG_RUNTIME_DIR/docker.sock" ]; then dockerd-rootless-setuptool.sh install || true; fi
                loginctl enable-linger "$(whoami)" || true
                systemctl --user daemon-reload || true
                systemctl --user enable --now docker || true
                export DOCKER_HOST="unix:///run/user/$(id -u)/docker.sock"
                ok2=0
                for i in $(seq 1 60); do docker info >/dev/null 2>&1 && ok2=1 && break || sleep 1; done
                if [ "$ok2" != "1" ]; then exit 1; fi
                USE_SUDO=""
              fi
              mkdir -p ~/.config/foodgram
              printf "USE_SUDO=%s\nDOCKER_HOST=%s\n" "$USE_SUDO" "$DOCKER_HOST" > ~/.config/foodgram/env
              chmod 600 ~/.config/foodgram/env
            '

  cleanup:
    needs: prepare_host
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            set -eu
            sudo -iu ${{ secrets.USER }} bash -lc '
              set -eu
              [ -f ~/.config/foodgram/env ] && set -a && . ~/.config/foodgram/env && set +a
              mkdir -p ~/foodgram
              cd ~/foodgram
              if [ -n "${USE_SUDO:-}" ]; then sudo docker compose -f docker-compose.production.yml down --remove-orphans || true; else docker compose -f docker-compose.production.yml down --remove-orphans || true; fi
              if [ -n "${USE_SUDO:-}" ]; then sudo fuser -k 8000/tcp || true; else fuser -k 8000/tcp || true; fi
              if [ -n "${USE_SUDO:-}" ]; then sudo docker container prune -f || true; else docker container prune -f || true; fi
              if [ -n "${USE_SUDO:-}" ]; then sudo docker image prune -f || true; else docker image prune -f || true; fi
              if [ -n "${USE_SUDO:-}" ]; then sudo docker network prune -f || true; else docker network prune -f || true; fi
            '

  deploy:
    runs-on: ubuntu-latest
    needs: [prepare_host, cleanup, build_backend, build_frontend, build_gateway]
    steps:
      - uses: actions/checkout@v3

      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            set -eu
            sudo mkdir -p /home/${{ secrets.USER }}/foodgram
            sudo chown -R ${{ secrets.USER }}:${{ secrets.USER }} /home/${{ secrets.USER }}/foodgram
            sudo -iu ${{ secrets.USER }} bash -lc '
              set -eu
              [ -f ~/.config/foodgram/env ] && set -a && . ~/.config/foodgram/env && set +a
              rm -f ~/foodgram/docker-compose.production.yml
            '

      - uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          source: "docker-compose.production.yml"
          target: "/home/${{ secrets.USER }}/foodgram"
          overwrite: true

      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            set -eu
            sudo -iu ${{ secrets.USER }} bash -lc '
              set -eu
              [ -f ~/.config/foodgram/env ] && set -a && . ~/.config/foodgram/env && set +a
              cd ~/foodgram
              if [ -n "${DOCKER_HOST:-}" ]; then export DOCKER_HOST="$DOCKER_HOST"; fi
              if [ -n "${USE_SUDO:-}" ]; then echo "${{ secrets.DOCKER_PASSWORD }}" | sudo docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin || true; else echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin || true; fi
              if [ -n "${USE_SUDO:-}" ]; then sudo docker compose -f docker-compose.production.yml pull; else docker compose -f docker-compose.production.yml pull; fi
              if [ -n "${USE_SUDO:-}" ]; then sudo docker compose -f docker-compose.production.yml down --remove-orphans || true; else docker compose -f docker-compose.production.yml down --remove-orphans || true; fi
              if [ -n "${USE_SUDO:-}" ]; then sudo docker compose -f docker-compose.production.yml up -d --force-recreate --remove-orphans || true; else docker compose -f docker-compose.production.yml up -d --force-recreate --remove-orphans || true; fi
              if [ -n "${USE_SUDO:-}" ]; then sudo docker compose -f docker-compose.production.yml exec -T db bash -lc "until pg_isready -U \\"$POSTGRES_USER\\" -d \\"$POSTGRES_DB\\"; do sleep 1; done"; else docker compose -f docker-compose.production.yml exec -T db bash -lc "until pg_isready -U \\"$POSTGRES_USER\\" -d \\"$POSTGRES_DB\\"; do sleep 1; done"; fi
              if [ -n "${USE_SUDO:-}" ]; then sudo docker compose -f docker-compose.production.yml exec -T backend python manage.py migrate; else docker compose -f docker-compose.production.yml exec -T backend python manage.py migrate; fi
              if [ -n "${USE_SUDO:-}" ]; then sudo docker compose -f docker-compose.production.yml exec -T backend python manage.py collectstatic --noinput; else docker compose -f docker-compose.production.yml exec -T backend python manage.py collectstatic --noinput; fi
              if [ -n "${USE_SUDO:-}" ]; then sudo docker compose -f docker-compose.production.yml exec -T backend bash -lc "rm -rf /backend_static/* && cp -r /app/static/. /backend_static/"; else docker compose -f docker-compose.production.yml exec -T backend bash -lc "rm -rf /backend_static/* && cp -r /app/static/. /backend_static/"; fi
              if [ -n "${USE_SUDO:-}" ]; then sudo docker compose -f docker-compose.production.yml exec -T frontend bash -lc "rm -rf /static/* && cp -r /app/build/static/. /static/"; else docker compose -f docker-compose.production.yml exec -T frontend bash -lc "rm -rf /static/* && cp -r /app/build/static/. /static/"; fi
              if [ -n "${USE_SUDO:-}" ]; then sudo docker compose -f docker-compose.production.yml exec -T gateway sh -lc "for i in $(seq 1 60); do wget -qO- http://frontend:9000/ >/dev/null 2>&1 && exit 0 || sleep 1; done; exit 1"; else docker compose -f docker-compose.production.yml exec -T gateway sh -lc "for i in $(seq 1 60); do wget -qO- http://frontend:9000/ >/dev/null 2>&1 && exit 0 || sleep 1; done; exit 1"; fi
              curl -sfI http://127.0.0.1:8000/ >/dev/null
            '

  notify:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: Foodgram деплой выполнен
