name: Foodgram CI/CD
on: [push]

jobs:
  tests:
    runs-on: ubuntu-22.04
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: foodgram_user
          POSTGRES_PASSWORD: foodgram_password
          POSTGRES_DB: foodgram
        ports: [ "5432:5432" ]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8==6.0.0 flake8-isort==6.0.0
          pip install -r ./backend/requirements.txt
      - name: Test with flake8 and Django tests
        env:
          POSTGRES_USER: foodgram_user
          POSTGRES_PASSWORD: foodgram_password
          POSTGRES_DB: foodgram
          DB_HOST: 127.0.0.1
          DB_PORT: 5432
          DJANGO_SECRET_KEY: dummy-secret-key
          DJANGO_DEBUG: 'False'
          ALLOWED_HOSTS: 'localhost,127.0.0.1'
        run: |
          python -m flake8 backend/
          cd backend/
          python manage.py test

  build_and_push_backend:
    name: Build & Push Backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v5
        with:
          context: backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/foodgram_backend:latest

  build_and_push_frontend:
    name: Build & Push Frontend
    runs-on: ubuntu-latest
    needs: build_and_push_backend
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v5
        with:
          context: frontend
          file: frontend/Dockerfile.prod
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/foodgram_frontend:latest

  deploy:
    name: Deploy to VM
    runs-on: ubuntu-latest
    needs: build_and_push_frontend
    steps:
      - name: SSH deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            set -e
            cd /home/${{ secrets.USER }}/foodgram/infra

            if [ -d ../.git ]; then
              cd ..
              sudo git pull || true
              cd infra
            fi

            sudo sed -i 's/\r$//' docker-compose.production.yml || true
            sudo sed -i 's/\r$//' nginx.production.conf || true

            sudo rm -f .env
            sudo touch .env
            printf "SECRET_KEY=%s\n"            "${{ secrets.SECRET_KEY }}"      | sudo tee -a .env >/dev/null
            printf "DEBUG=%s\n"                 "False"                           | sudo tee -a .env >/dev/null
            printf "DB_ENGINE=%s\n"             "${{ secrets.DB_ENGINE }}"        | sudo tee -a .env >/dev/null
            printf "DB_NAME=%s\n"               "${{ secrets.DB_NAME }}"          | sudo tee -a .env >/dev/null
            printf "POSTGRES_USER=%s\n"         "${{ secrets.POSTGRES_USER }}"    | sudo tee -a .env >/dev/null
            printf "POSTGRES_PASSWORD=%s\n"     "${{ secrets.POSTGRES_PASSWORD }}"| sudo tee -a .env >/dev/null
            printf "DB_HOST=%s\n"               "${{ secrets.DB_HOST }}"          | sudo tee -a .env >/dev/null
            printf "DB_PORT=%s\n"               "${{ secrets.DB_PORT }}"          | sudo tee -a .env >/dev/null
            printf "DOCKER_USERNAME=%s\n"       "${{ secrets.DOCKER_USERNAME }}"  | sudo tee -a .env >/dev/null

            sudo docker-compose -f docker-compose.production.yml config | awk '/image:/{print}'

            sudo docker-compose -f docker-compose.production.yml down
            sudo docker-compose -f docker-compose.production.yml pull
            sudo docker-compose -f docker-compose.production.yml up -d --build

            sudo docker-compose -f docker-compose.production.yml exec -T backend python manage.py migrate
            sudo docker-compose -f docker-compose.production.yml exec -T backend python manage.py collectstatic --no-input
            sudo docker-compose -f docker-compose.production.yml exec -T backend python manage.py load_ingredients

  notify:
    name: Telegram Notify
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: "Foodgram: деплой успешно выполнен ✅"
